remote_theme: pages-themes/architect@v0.2.0
title: mostly ramblings
author: malevy
email: malevy@outlook.gcom
description: > # this means to ignore newlines until "baseurl:"
  my own little place on the web for whatever nonsense flows from by brain

# social links
twitter_username: malevy # DO NOT include the @ character, or else the build will fail!
github_username:  malevy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
